

# This file was *autogenerated* from the file cuspidal_reps.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10)# Preliminaries

# Field and general linear group
q = _sage_const_3 
K = GF(q)
G = GL(_sage_const_2 , K)

# Borel subgroup
a = K.zeta()
MS = MatrixSpace(K, _sage_const_2 )
gens = [MS([[_sage_const_1 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ]]),MS([[a,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ]]), MS([[_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,a]])]
B = G.subgroup(gens)

# U subgroup
gens = [MS([[_sage_const_1 ,x],[_sage_const_0 ,_sage_const_1 ]]) for x in K]
U = G.subgroup(gens)

# Creating vector space for induced rep
dim = (q+_sage_const_1 ) * (q-_sage_const_1 )**_sage_const_2 
V = VectorSpace(QQbar, dim)
H = Hom(V, V)


# The chosen coset representations of U\G
cosetRepsB = []
for x in K:
    rep = G(MS([[_sage_const_1 ,_sage_const_0 ],[-x,_sage_const_1 ]]))
    cosetRepsB.append(rep)
rep = G(MS([[_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ]]))
cosetRepsB.append(rep)

cosetRepsD = []
for x in K:
    if x != _sage_const_0 :
        for y in K:
            if y != _sage_const_0 :
                rep = G(MS([[_sage_const_1  / x, _sage_const_0 ],[_sage_const_0 , _sage_const_1  / y]]))
                cosetRepsD.append(rep)

repToIndex = {}
index = _sage_const_0 

cosetReps = []
for gRep in cosetRepsB:
    for dRep in cosetRepsD:
        rep = dRep * gRep
        cosetReps.append(rep)
        repToIndex[rep] = index
        index = index + _sage_const_1 
print(cosetReps)
print(len(cosetReps))









ct = U.character_table()
#print(ct)

#for chi in ct:
#    print(U.character(chi).induct(G).values())
# Notice this induced rep same for all non-unit chars!!!

chi = U.character(ct[_sage_const_1 ])
print(chi.values())






# NEED TO CHANGE THIS!!!

# Takes in element g from G and returns the corresponding representative in U\G
def toRepresentative(g):
    gRep = -_sage_const_1 
    if g.inverse().matrix()[_sage_const_0 ][_sage_const_0 ] == _sage_const_0 :
        gRep = G(MS([[_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ]]))
    else:
        x = (K.one() / g.inverse().matrix()[_sage_const_0 ][_sage_const_0 ]) * g.inverse().matrix()[_sage_const_1 ][_sage_const_0 ]
        gRep = G(MS([[_sage_const_1 ,_sage_const_0 ],[x,_sage_const_1 ]]))

    if gRep == -_sage_const_1 :
        print("AHHHHHHHH")

    b = gRep.inverse() * g.inverse()
    d = G(MS([[b.matrix()[_sage_const_0 ][_sage_const_0 ], _sage_const_0 ], [_sage_const_0 , b.matrix()[_sage_const_1 ][_sage_const_1 ]]]))

    u = gRep * d
    return u.inverse()
# Constant time


# Gives the G action result of group element g from G onto vector v from V
# Uses globally defined character chi
# Uses globally defined vector space V
def gAction(g, vec):
    newVec = V([_sage_const_0 ] * dim)
    for i in range(_sage_const_0 , dim):
        if vec[i] == _sage_const_0 :
            continue
        newRep = toRepresentative(cosetReps[i] * g.inverse())
        #print(newRep)
        u = cosetReps[i] * g.inverse() * newRep.inverse()
        
        newIndex = repToIndex[newRep]

        newVec[newIndex] = newVec[newIndex] + chi(u.inverse()) * vec[i]
        #print(chi(u.inverse()) * vec[i])

    return newVec
# Linear time

# Prints the matrix nicely, rounding the actual digits and displays zero as zero
def printMatrix(M):
    decimalPlaces = _sage_const_4 
    print("Printing matrix:")
    for row in M:
        print("[", end="")
        for elem in row:
            temp = _sage_const_0 
            if elem != _sage_const_0 :
                temp = round(elem.real(), decimalPlaces) + round(elem.imag(), decimalPlaces) * I
            print("{:<{mx}}".format(temp, mx=_sage_const_10 ), end="\t")
        print("]")
# Should automate length of mx

# Finds eigenSpaces of particular g given the character chi for which this representations is induced
def eigenVectors(g):
    img = [gAction(g, basisVec) for basisVec in V.basis()]
    f = H(img)
    M = f.matrix()
    eigenSpaces = M.eigenvectors_left()
    return eigenSpaces

# Goes through eigenvectors, chooses q-1, 1, and q+1 of them to form a set of spaces
def findInvariantSubspacesH(g):

    # List of eigenvectors:
    temp = eigenVectors(g)
    listVecs = []
    for t in temp:
        listVecs = listVecs + t[_sage_const_1 ]
    #print(len(listVecs))

    sol = set()

    # q-1:
    s = Subsets(listVecs, q-_sage_const_1 )
    #print(s.cardinality())
    for gens in s:
        v = V.subspace(gens)
        sol.add(v)

    # q:
    s = Subsets(listVecs, q)
    #print(s.cardinality())
    for gens in s:
        v = V.subspace(gens)
        sol.add(v)

    # q+1:
    s = Subsets(listVecs, q+_sage_const_1 )
    #print(s.cardinality())
    for gens in s:
        v = V.subspace(gens)
        sol.add(v)

    return sol
# Very not efficient

# Iterates through all g, finds all invariant subspaces, and finds intersections
def findInvariantSubspaces():
    memorySet = set()
    g = G.random_element()
    s = findInvariantSubspacesH(g)
    memorySet.update(s)

    for elem in G:
        print("Looking at element:")
        print(elem)
        print("Currently memorySet has " + str(len(memorySet)) + " elements")
        if len(memorySet) == q - _sage_const_1  + (q**_sage_const_2  - q + q**_sage_const_2  - _sage_const_3 *q + _sage_const_2 ) / _sage_const_2 :
            break
        
        s = findInvariantSubspacesH(elem)

        tempSet = set()
        for ogSpace in memorySet:
            for newSpace in s:
                t = ogSpace.intersection(newSpace)

                if t.dimension() == q-_sage_const_1  or t.dimension() == q or t.dimension() == q+_sage_const_1 :
                    tempSet.add(t)
        #print(tempSet)
        memorySet = tempSet
        
    print(memorySet)
# Stupidly ineffient




'''
g = G(MS([[1, 2], [1, 1]]))
print(g)

print(toRepresentative(g))
print(g * toRepresentative(g).inverse())

vec = V.random_element()

print(vec)
print(gAction(g, vec))
'''






g = G(MS([[_sage_const_1 , _sage_const_2 ], [_sage_const_1 , _sage_const_1 ]]))
print(g)

#print(eigenVectors(g))

findInvariantSubspaces()

