

# This file was *autogenerated* from the file decomposable_reps.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_15 = Integer(15)
# Preliminaries

# Field and general linear group
q = _sage_const_4 
K = GF(q)
G = GL(_sage_const_2 , K)

# Borel subgroup
a = K.zeta()
MS = MatrixSpace(K, _sage_const_2 )
gens = [MS([[_sage_const_1 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ]]),MS([[a,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ]]), MS([[_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,a]])]
B = G.subgroup(gens)

# Creating vector space for induced rep
V = VectorSpace(CC, q+_sage_const_1 )

# The chosen coset representations 
# First q spots are of the form [[1, 0][-i, 1]] (i counts up from 0 to q-1)
# Last spot (index q) is w
cosetReps = []
repToIndex = {}
index = _sage_const_0 
for x in K:
    rep = G(MS([[_sage_const_1 ,_sage_const_0 ],[-x,_sage_const_1 ]]))
    cosetReps.append(rep)
    repToIndex[rep] = index
    #print(rep)
    index = index + _sage_const_1 
rep = G(MS([[_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ]]))
cosetReps.append(rep)
repToIndex[rep] = q
#print(cosetReps[q])










# Takes in character of B and returns if the induced representation is irreducible or not

def isInducedIrreducible(chi):
    induced_chi = chi.induct(G)
    return induced_chi.is_irreducible()
ct = B.character_table()
#print(ct)
badChars = []
goodChars = []
for i in range(_sage_const_0 , len(B.conjugacy_classes_representatives())):
    if ct[i][_sage_const_0 ] == _sage_const_1 :
        if isInducedIrreducible(B.character(ct[i])):
            goodChars.append(B.character(ct[i]))
        else:
            badChars.append(B.character(ct[i]))
chi = goodChars[_sage_const_0 ]
print(chi.values())

#print(len(goodChars))
#print(len(badChars))

# NOTICE - the induced reps of the goodChars are each counted twice, as two diff chars map to the same induced rep







# Takes in element g from G and returns the corresponding representative in B\G
def toRepresentative(g):
    if g.inverse().matrix()[_sage_const_0 ][_sage_const_0 ] == _sage_const_0 :
        return G(MS([[_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ]])).inverse()
    else:
        x = (K.one() / g.inverse().matrix()[_sage_const_0 ][_sage_const_0 ]) * g.inverse().matrix()[_sage_const_1 ][_sage_const_0 ]
        return G(MS([[_sage_const_1 ,_sage_const_0 ],[x,_sage_const_1 ]])).inverse()
# Constant time


# Gives the G action result of group element g from G onto vector v from V
# Uses globally defined character chi
# Uses globally defined vector space V
def gAction(g, vec):
    newVec = V([_sage_const_0 ] * (q+_sage_const_1 ))
    for i in range(_sage_const_0 , q+_sage_const_1 ):
        newRep = toRepresentative(cosetReps[i] * g.inverse())
        #print(newRep)
        b = cosetReps[i] * g.inverse() * newRep.inverse()
        
        newIndex = repToIndex[newRep]

        newVec[newIndex] = newVec[newIndex] + chi(b.inverse()) * vec[i]
        #print(chi(b.inverse()) * vec[i])

    return newVec
# Linear time

# Prints the matrix nicely, rounding the actual digits and displays zero as zero
def printMatrix(M):
    decimalPlaces = _sage_const_4 
    print("Printing matrix:")
    for row in M:
        for elem in row:
            temp = _sage_const_0 
            if elem != _sage_const_0 :
                temp = round(elem.real(), decimalPlaces) + round(elem.imag(), decimalPlaces) * I
            print("{:<{mx}}".format(temp, mx=_sage_const_15 ), end="\t")
        print("")
# Should automate length of mx



# PLAN:
# Take some g
# Compute it as matrix
# find eigenspaces
# take second g
# repeat process until only one eigenspace left

g = G.random_element()
#g = G([[1, 0], [0, 1]])

V = VectorSpace(QQbar, q+_sage_const_1 )
H = Hom(V, V)

print(H)
#print(H.domain())
#print(H.domain().basis())

for g in G:
    img = [gAction(g, V([_sage_const_0 ]*j+[_sage_const_1 ]+[_sage_const_0 ]*(q-j))) for j in range(q+_sage_const_1 )]
    f = H(img)
    M = f.matrix()
    printMatrix(M)





'''
def eigenVectors(g):
    img = [gAction(g, V([0]*j+[1]+[0]*(q-j))) for j in range(q+1)]
    f = H(img)
    M = f.matrix()
    eigenVecs = M.eigenvectors_left()
    return eigenVecs



memorySet = set()
g = G.random_element()
temp = eigenVectors(g)
for item in temp:
    memorySet.update(item[1])
memory = V.subspace([V(x) for x in memorySet])
print(memory)

count = 0
for g in G:
    temp = eigenVectors(g)
    tempSet = set()
    for item in temp:
        tempSet.update(item[1])
    tempVS = V.subspace([V(x) for x in tempSet])
    if count < 6:
        print("This is tempSet:")
        print(tempSet)
        print(tempVS)
    memory = memory.intersection(tempVS)
    print(memory)
    count = count + 1

print(memory)
'''

# THIS DOESNT WORK AT ALL, NEED TO INTERSECT EIGENSPACES!!!

